// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type ChatCompletionFunctionMessageParam struct {
	Content *string `json:"content"`
	Name    string  `json:"name"`
	role    string  `const:"function" json:"role"`
}

func (c ChatCompletionFunctionMessageParam) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatCompletionFunctionMessageParam) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *ChatCompletionFunctionMessageParam) GetContent() *string {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *ChatCompletionFunctionMessageParam) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ChatCompletionFunctionMessageParam) GetRole() string {
	return "function"
}
