// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type ChatCompletionNamedToolChoiceParam struct {
	Function OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction `json:"function"`
	type_    string                                                    `const:"function" json:"type"`
}

func (c ChatCompletionNamedToolChoiceParam) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatCompletionNamedToolChoiceParam) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *ChatCompletionNamedToolChoiceParam) GetFunction() OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction {
	if o == nil {
		return OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction{}
	}
	return o.Function
}

func (o *ChatCompletionNamedToolChoiceParam) GetType() string {
	return "function"
}
