// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type ChatCompletionMessageToolCall struct {
	ID                   string         `json:"id"`
	Function             FunctionOutput `json:"function"`
	type_                string         `const:"function" json:"type"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

func (c ChatCompletionMessageToolCall) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatCompletionMessageToolCall) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ChatCompletionMessageToolCall) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ChatCompletionMessageToolCall) GetFunction() FunctionOutput {
	if o == nil {
		return FunctionOutput{}
	}
	return o.Function
}

func (o *ChatCompletionMessageToolCall) GetType() string {
	return "function"
}

func (o *ChatCompletionMessageToolCall) GetAdditionalProperties() map[string]any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
