// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type ChatCompletionContentPartRefusalParam struct {
	Refusal string `json:"refusal"`
	type_   string `const:"refusal" json:"type"`
}

func (c ChatCompletionContentPartRefusalParam) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatCompletionContentPartRefusalParam) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *ChatCompletionContentPartRefusalParam) GetRefusal() string {
	if o == nil {
		return ""
	}
	return o.Refusal
}

func (o *ChatCompletionContentPartRefusalParam) GetType() string {
	return "refusal"
}
