// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type ChatCompletionMessageToolCallParam struct {
	ID       string                                                    `json:"id"`
	Function OpenaiTypesChatChatCompletionMessageToolCallParamFunction `json:"function"`
	type_    string                                                    `const:"function" json:"type"`
}

func (c ChatCompletionMessageToolCallParam) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatCompletionMessageToolCallParam) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ChatCompletionMessageToolCallParam) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ChatCompletionMessageToolCallParam) GetFunction() OpenaiTypesChatChatCompletionMessageToolCallParamFunction {
	if o == nil {
		return OpenaiTypesChatChatCompletionMessageToolCallParamFunction{}
	}
	return o.Function
}

func (o *ChatCompletionMessageToolCallParam) GetType() string {
	return "function"
}
