// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type CompletionUsage struct {
	CompletionTokens        int64                    `json:"completion_tokens"`
	PromptTokens            int64                    `json:"prompt_tokens"`
	TotalTokens             int64                    `json:"total_tokens"`
	CompletionTokensDetails *CompletionTokensDetails `json:"completion_tokens_details,omitempty"`
	PromptTokensDetails     *PromptTokensDetails     `json:"prompt_tokens_details,omitempty"`
	AdditionalProperties    map[string]any           `additionalProperties:"true" json:"-"`
}

func (c CompletionUsage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CompletionUsage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CompletionUsage) GetCompletionTokens() int64 {
	if o == nil {
		return 0
	}
	return o.CompletionTokens
}

func (o *CompletionUsage) GetPromptTokens() int64 {
	if o == nil {
		return 0
	}
	return o.PromptTokens
}

func (o *CompletionUsage) GetTotalTokens() int64 {
	if o == nil {
		return 0
	}
	return o.TotalTokens
}

func (o *CompletionUsage) GetCompletionTokensDetails() *CompletionTokensDetails {
	if o == nil {
		return nil
	}
	return o.CompletionTokensDetails
}

func (o *CompletionUsage) GetPromptTokensDetails() *PromptTokensDetails {
	if o == nil {
		return nil
	}
	return o.PromptTokensDetails
}

func (o *CompletionUsage) GetAdditionalProperties() map[string]any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
