// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

type CreateKnowledgeBaseResponse struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"created_at"`
	EmbeddingModel string    `json:"embedding_model"`
}

func (c CreateKnowledgeBaseResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateKnowledgeBaseResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateKnowledgeBaseResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateKnowledgeBaseResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateKnowledgeBaseResponse) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *CreateKnowledgeBaseResponse) GetEmbeddingModel() string {
	if o == nil {
		return ""
	}
	return o.EmbeddingModel
}
