// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateDatasetEntryRequest struct {
	// The input to the dataset entry
	Input any `json:"input"`
	// The output to the dataset entry
	Output any `json:"output"`
	// The expected output to the dataset entry, this is an optionally edited version of the output
	Expected any `json:"expected,omitempty"`
	// The comment to the dataset entry
	Comment *string `json:"comment,omitempty"`
}

func (o *CreateDatasetEntryRequest) GetInput() any {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *CreateDatasetEntryRequest) GetOutput() any {
	if o == nil {
		return nil
	}
	return o.Output
}

func (o *CreateDatasetEntryRequest) GetExpected() any {
	if o == nil {
		return nil
	}
	return o.Expected
}

func (o *CreateDatasetEntryRequest) GetComment() *string {
	if o == nil {
		return nil
	}
	return o.Comment
}
