// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Example struct {
	Input   any     `json:"input"`
	Output  any     `json:"output"`
	Comment *string `json:"comment,omitempty"`
}

func (o *Example) GetInput() any {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *Example) GetOutput() any {
	if o == nil {
		return nil
	}
	return o.Output
}

func (o *Example) GetComment() *string {
	if o == nil {
		return nil
	}
	return o.Comment
}
