// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ExampleIn struct {
	Input   any     `json:"input"`
	Output  any     `json:"output"`
	Comment *string `json:"comment,omitempty"`
}

func (o *ExampleIn) GetInput() any {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *ExampleIn) GetOutput() any {
	if o == nil {
		return nil
	}
	return o.Output
}

func (o *ExampleIn) GetComment() *string {
	if o == nil {
		return nil
	}
	return o.Comment
}
