// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type File struct {
	File  FileFile `json:"file"`
	type_ string   `const:"file" json:"type"`
}

func (f File) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *File) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *File) GetFile() FileFile {
	if o == nil {
		return FileFile{}
	}
	return o.File
}

func (o *File) GetType() string {
	return "file"
}
