// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetCustomModelResponse struct {
	// The ID of the custom language model
	ID string `json:"id"`
	// The name of the custom language model
	Name string `json:"name"`
	// The identifier of the custom language model
	Identifier string `json:"identifier"`
	// Extra metadata about the custom language model
	Extra map[string]any `json:"extra,omitempty"`
}

func (o *GetCustomModelResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetCustomModelResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GetCustomModelResponse) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *GetCustomModelResponse) GetExtra() map[string]any {
	if o == nil {
		return nil
	}
	return o.Extra
}
