// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

type GetKnowledgeBaseResponse struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"created_at"`
	EmbeddingModel string    `json:"embedding_model"`
}

func (g GetKnowledgeBaseResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetKnowledgeBaseResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetKnowledgeBaseResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetKnowledgeBaseResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GetKnowledgeBaseResponse) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *GetKnowledgeBaseResponse) GetEmbeddingModel() string {
	if o == nil {
		return ""
	}
	return o.EmbeddingModel
}
