// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

type GetUsageResultItem struct {
	// The start time of the time bucket
	TimeBucket time.Time `json:"time_bucket"`
	// The cost in USD for the time bucket
	Cost                 string         `json:"cost"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

func (g GetUsageResultItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUsageResultItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetUsageResultItem) GetTimeBucket() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.TimeBucket
}

func (o *GetUsageResultItem) GetCost() string {
	if o == nil {
		return ""
	}
	return o.Cost
}

func (o *GetUsageResultItem) GetAdditionalProperties() map[string]any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
