// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type JSONSchema struct {
	Name        string         `json:"name"`
	Description *string        `json:"description,omitempty"`
	Schema      map[string]any `json:"schema,omitempty"`
	Strict      *bool          `json:"strict,omitempty"`
}

func (o *JSONSchema) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *JSONSchema) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *JSONSchema) GetSchema() map[string]any {
	if o == nil {
		return nil
	}
	return o.Schema
}

func (o *JSONSchema) GetStrict() *bool {
	if o == nil {
		return nil
	}
	return o.Strict
}
