// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

type ListFunctionRevisionResponse struct {
	ID            string         `json:"id"`
	Configuration map[string]any `json:"configuration"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     *time.Time     `json:"updated_at,omitempty"`
}

func (l ListFunctionRevisionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListFunctionRevisionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListFunctionRevisionResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ListFunctionRevisionResponse) GetConfiguration() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.Configuration
}

func (o *ListFunctionRevisionResponse) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *ListFunctionRevisionResponse) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
