// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListLanguageModelsResponse struct {
	// The hosting provider of the model
	HostingProvider string `json:"hosting_provider"`
	// The name of the model
	Name string `json:"name"`
	// The location of the model
	Location string `json:"location"`
	// The cost in USD per token for input
	InputCostPerToken *float64 `json:"input_cost_per_token,omitempty"`
	// The cost in USD per token for output
	OutputCostPerToken *float64 `json:"output_cost_per_token,omitempty"`
}

func (o *ListLanguageModelsResponse) GetHostingProvider() string {
	if o == nil {
		return ""
	}
	return o.HostingProvider
}

func (o *ListLanguageModelsResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ListLanguageModelsResponse) GetLocation() string {
	if o == nil {
		return ""
	}
	return o.Location
}

func (o *ListLanguageModelsResponse) GetInputCostPerToken() *float64 {
	if o == nil {
		return nil
	}
	return o.InputCostPerToken
}

func (o *ListLanguageModelsResponse) GetOutputCostPerToken() *float64 {
	if o == nil {
		return nil
	}
	return o.OutputCostPerToken
}
