// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

type ListTracesResponse struct {
	// The id of the trace
	ID string `json:"id"`
	// The start time of the trace
	StartTime *time.Time `json:"start_time,omitempty"`
	// The end time of the trace
	EndTime *time.Time `json:"end_time,omitempty"`
	// The duration of the trace
	DurationMs *int64 `json:"duration_ms,omitempty"`
	// The status of the trace
	Status *string `json:"status,omitempty"`
	// The name of the trace, set to the name of the root span of the trace
	Name *string `json:"name,omitempty"`
	// The input of the trace, set to the input of the root span of the trace
	Input *string `json:"input,omitempty"`
	// The output of the trace, set to the output of the root span of the trace
	Output *string `json:"output,omitempty"`
	// The total tokens of the trace
	TotalTokens *int64 `json:"total_tokens,omitempty"`
}

func (l ListTracesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTracesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListTracesResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ListTracesResponse) GetStartTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.StartTime
}

func (o *ListTracesResponse) GetEndTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndTime
}

func (o *ListTracesResponse) GetDurationMs() *int64 {
	if o == nil {
		return nil
	}
	return o.DurationMs
}

func (o *ListTracesResponse) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *ListTracesResponse) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ListTracesResponse) GetInput() *string {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *ListTracesResponse) GetOutput() *string {
	if o == nil {
		return nil
	}
	return o.Output
}

func (o *ListTracesResponse) GetTotalTokens() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalTokens
}
