// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListFunctionsResponseItem struct {
	// The ID of the function
	ID string `json:"id"`
	// The name of the function
	Name string `json:"name"`
	// The description of the function
	Description *string `json:"description,omitempty"`
	// The instructions of the function
	Instructions *string `json:"instructions,omitempty"`
	// The model of the function
	Model *TModel `json:"model,omitempty"`
	// The ID of the latest revision of the function
	RevisionID string `json:"revision_id"`
}

func (o *ListFunctionsResponseItem) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ListFunctionsResponseItem) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ListFunctionsResponseItem) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ListFunctionsResponseItem) GetInstructions() *string {
	if o == nil {
		return nil
	}
	return o.Instructions
}

func (o *ListFunctionsResponseItem) GetModel() *TModel {
	if o == nil {
		return nil
	}
	return o.Model
}

func (o *ListFunctionsResponseItem) GetRevisionID() string {
	if o == nil {
		return ""
	}
	return o.RevisionID
}
