// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Meta struct {
	// Total number of items in the collection
	TotalCount int64 `json:"total_count"`
}

func (o *Meta) GetTotalCount() int64 {
	if o == nil {
		return 0
	}
	return o.TotalCount
}
