// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Model struct {
	Name         string         `json:"name"`
	ExtraHeaders map[string]any `json:"extra_headers,omitempty"`
	Options      map[string]any `json:"options,omitempty"`
}

func (o *Model) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Model) GetExtraHeaders() map[string]any {
	if o == nil {
		return nil
	}
	return o.ExtraHeaders
}

func (o *Model) GetOptions() map[string]any {
	if o == nil {
		return nil
	}
	return o.Options
}
