// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaginatedResponseGetDatasetEntriesResponse struct {
	Meta Meta `json:"meta"`
	// List of items returned in the response
	Data []GetDatasetEntriesResponse `json:"data"`
}

func (o *PaginatedResponseGetDatasetEntriesResponse) GetMeta() Meta {
	if o == nil {
		return Meta{}
	}
	return o.Meta
}

func (o *PaginatedResponseGetDatasetEntriesResponse) GetData() []GetDatasetEntriesResponse {
	if o == nil {
		return []GetDatasetEntriesResponse{}
	}
	return o.Data
}
