// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaginatedResponseListKnowledgeBasesResponse struct {
	Meta Meta `json:"meta"`
	// List of items returned in the response
	Data []ListKnowledgeBasesResponse `json:"data"`
}

func (o *PaginatedResponseListKnowledgeBasesResponse) GetMeta() Meta {
	if o == nil {
		return Meta{}
	}
	return o.Meta
}

func (o *PaginatedResponseListKnowledgeBasesResponse) GetData() []ListKnowledgeBasesResponse {
	if o == nil {
		return []ListKnowledgeBasesResponse{}
	}
	return o.Data
}
