// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaginatedResponseListTracesResponse struct {
	Meta Meta `json:"meta"`
	// List of items returned in the response
	Data []ListTracesResponse `json:"data"`
}

func (o *PaginatedResponseListTracesResponse) GetMeta() Meta {
	if o == nil {
		return Meta{}
	}
	return o.Meta
}

func (o *PaginatedResponseListTracesResponse) GetData() []ListTracesResponse {
	if o == nil {
		return []ListTracesResponse{}
	}
	return o.Data
}
