// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaginatedResponseListLanguageModelsResponse struct {
	Meta Meta `json:"meta"`
	// List of items returned in the response
	Data []ListLanguageModelsResponse `json:"data"`
}

func (o *PaginatedResponseListLanguageModelsResponse) GetMeta() Meta {
	if o == nil {
		return Meta{}
	}
	return o.Meta
}

func (o *PaginatedResponseListLanguageModelsResponse) GetData() []ListLanguageModelsResponse {
	if o == nil {
		return []ListLanguageModelsResponse{}
	}
	return o.Data
}
