// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaginatedResponseListFunctionsResponseItem struct {
	Meta Meta `json:"meta"`
	// List of items returned in the response
	Data []ListFunctionsResponseItem `json:"data"`
}

func (o *PaginatedResponseListFunctionsResponseItem) GetMeta() Meta {
	if o == nil {
		return Meta{}
	}
	return o.Meta
}

func (o *PaginatedResponseListFunctionsResponseItem) GetData() []ListFunctionsResponseItem {
	if o == nil {
		return []ListFunctionsResponseItem{}
	}
	return o.Data
}
