// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type ResponseFormatJSONObject struct {
	type_ string `const:"json_object" json:"type"`
}

func (r ResponseFormatJSONObject) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResponseFormatJSONObject) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *ResponseFormatJSONObject) GetType() string {
	return "json_object"
}
