// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SaveToDatasetResponse struct {
	// The ID of the dataset
	DatasetID string `json:"dataset_id"`
	// The ID of the dataset entry
	DatasetEntryID string `json:"dataset_entry_id"`
	// The input of the dataset entry
	Input *string `json:"input,omitempty"`
	// The output of the dataset entry
	Output *string `json:"output,omitempty"`
	// The expected output of the dataset entry
	Expected *string `json:"expected,omitempty"`
	// The comment of the dataset entry
	Comment *string `json:"comment,omitempty"`
}

func (o *SaveToDatasetResponse) GetDatasetID() string {
	if o == nil {
		return ""
	}
	return o.DatasetID
}

func (o *SaveToDatasetResponse) GetDatasetEntryID() string {
	if o == nil {
		return ""
	}
	return o.DatasetEntryID
}

func (o *SaveToDatasetResponse) GetInput() *string {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *SaveToDatasetResponse) GetOutput() *string {
	if o == nil {
		return nil
	}
	return o.Output
}

func (o *SaveToDatasetResponse) GetExpected() *string {
	if o == nil {
		return nil
	}
	return o.Expected
}

func (o *SaveToDatasetResponse) GetComment() *string {
	if o == nil {
		return nil
	}
	return o.Comment
}
