// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateCustomModelRequest struct {
	// The name of the custom language model
	Name *string `json:"name,omitempty"`
	// The identifier of the custom language model
	Identifier *string `json:"identifier,omitempty"`
	// Extra metadata about the custom language model
	Extra map[string]any `json:"extra,omitempty"`
	// The API key of the custom language model
	APIKey *string `json:"api_key,omitempty"`
}

func (o *UpdateCustomModelRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateCustomModelRequest) GetIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.Identifier
}

func (o *UpdateCustomModelRequest) GetExtra() map[string]any {
	if o == nil {
		return nil
	}
	return o.Extra
}

func (o *UpdateCustomModelRequest) GetAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.APIKey
}
