// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateFunctionRequest struct {
	// The name of the function. Must be unique within the project and can only contain letters, numbers, underscores and hyphens.
	Name *string `json:"name,omitempty"`
	// Optional description of the function. This is used to describe the function to a user.
	Description *string `json:"description,omitempty"`
	// The instructions for the function, this is the prompt that will be sent to the model to complete the task. Recommended to be concise and to the point
	Instructions *string `json:"instructions,omitempty"`
	// Optional input schema for the function. Can preferably include field descriptions to allow the model to reason about the input variables. Schema is validated against the input data and issues an error if it does not match. With the Opper SDKs you can define these schemas through libraries like Pydantic and Zod. For schemas with definitions, prefer using '$defs' and '#/$defs/...' references.
	InputSchema map[string]any `json:"input_schema,omitempty"`
	// Optional output schema for the function. Can preferably include field descriptions to allow the model to reason about the output variables. Schema is validated against the output data and issues an error if it does not match. With the Opper SDKs you can define these schemas through libraries like Pydantic and Zod. For schemas with definitions, prefer using '$defs' and '#/$defs/...' references.
	OutputSchema map[string]any `json:"output_schema,omitempty"`
	// Optionally provide a model to use for completing the task. If not provided, a default model will be used. Currently the default model is `azure/gpt-4o-eu`
	Model *TModel `json:"model,omitempty"`
	// Optional configuration for the function.Configuration is a dictionary of key-value pairs that can be used to override the default configuration for the function.
	Configuration map[string]any `json:"configuration,omitempty"`
}

func (o *UpdateFunctionRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateFunctionRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateFunctionRequest) GetInstructions() *string {
	if o == nil {
		return nil
	}
	return o.Instructions
}

func (o *UpdateFunctionRequest) GetInputSchema() map[string]any {
	if o == nil {
		return nil
	}
	return o.InputSchema
}

func (o *UpdateFunctionRequest) GetOutputSchema() map[string]any {
	if o == nil {
		return nil
	}
	return o.OutputSchema
}

func (o *UpdateFunctionRequest) GetModel() *TModel {
	if o == nil {
		return nil
	}
	return o.Model
}

func (o *UpdateFunctionRequest) GetConfiguration() map[string]any {
	if o == nil {
		return nil
	}
	return o.Configuration
}
