// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CallFunctionRevisionFunctionsFunctionIDCallRevisionIDPostRequest struct {
	// The id of the function to call
	FunctionID string `pathParam:"style=simple,explode=false,name=function_id"`
	// The id of the revision to call
	RevisionID                                 string                                                `pathParam:"style=simple,explode=false,name=revision_id"`
	AppAPIPublicV2FunctionsCallFunctionRequest components.AppAPIPublicV2FunctionsCallFunctionRequest `request:"mediaType=application/json"`
}

func (o *CallFunctionRevisionFunctionsFunctionIDCallRevisionIDPostRequest) GetFunctionID() string {
	if o == nil {
		return ""
	}
	return o.FunctionID
}

func (o *CallFunctionRevisionFunctionsFunctionIDCallRevisionIDPostRequest) GetRevisionID() string {
	if o == nil {
		return ""
	}
	return o.RevisionID
}

func (o *CallFunctionRevisionFunctionsFunctionIDCallRevisionIDPostRequest) GetAppAPIPublicV2FunctionsCallFunctionRequest() components.AppAPIPublicV2FunctionsCallFunctionRequest {
	if o == nil {
		return components.AppAPIPublicV2FunctionsCallFunctionRequest{}
	}
	return o.AppAPIPublicV2FunctionsCallFunctionRequest
}

type CallFunctionRevisionFunctionsFunctionIDCallRevisionIDPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	AppAPIPublicV2FunctionsCallFunctionResponse *components.AppAPIPublicV2FunctionsCallFunctionResponse
}

func (o *CallFunctionRevisionFunctionsFunctionIDCallRevisionIDPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CallFunctionRevisionFunctionsFunctionIDCallRevisionIDPostResponse) GetAppAPIPublicV2FunctionsCallFunctionResponse() *components.AppAPIPublicV2FunctionsCallFunctionResponse {
	if o == nil {
		return nil
	}
	return o.AppAPIPublicV2FunctionsCallFunctionResponse
}
