// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateEmbeddingEmbeddingsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	CreateEmbeddingResponse *components.CreateEmbeddingResponse
}

func (o *CreateEmbeddingEmbeddingsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateEmbeddingEmbeddingsPostResponse) GetCreateEmbeddingResponse() *components.CreateEmbeddingResponse {
	if o == nil {
		return nil
	}
	return o.CreateEmbeddingResponse
}
