// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateFunctionFunctionsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	CreateFunctionResponse *components.CreateFunctionResponse
}

func (o *CreateFunctionFunctionsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateFunctionFunctionsPostResponse) GetCreateFunctionResponse() *components.CreateFunctionResponse {
	if o == nil {
		return nil
	}
	return o.CreateFunctionResponse
}
