// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateDatasetEntryDatasetsDatasetIDPostRequest struct {
	// The id of the dataset
	DatasetID                 string                               `pathParam:"style=simple,explode=false,name=dataset_id"`
	CreateDatasetEntryRequest components.CreateDatasetEntryRequest `request:"mediaType=application/json"`
}

func (o *CreateDatasetEntryDatasetsDatasetIDPostRequest) GetDatasetID() string {
	if o == nil {
		return ""
	}
	return o.DatasetID
}

func (o *CreateDatasetEntryDatasetsDatasetIDPostRequest) GetCreateDatasetEntryRequest() components.CreateDatasetEntryRequest {
	if o == nil {
		return components.CreateDatasetEntryRequest{}
	}
	return o.CreateDatasetEntryRequest
}

type CreateDatasetEntryDatasetsDatasetIDPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	CreateDatasetEntryResponse *components.CreateDatasetEntryResponse
}

func (o *CreateDatasetEntryDatasetsDatasetIDPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateDatasetEntryDatasetsDatasetIDPostResponse) GetCreateDatasetEntryResponse() *components.CreateDatasetEntryResponse {
	if o == nil {
		return nil
	}
	return o.CreateDatasetEntryResponse
}
