// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateMetricSpansSpanIDMetricsPostRequest struct {
	// The id of the span
	SpanID                  string                             `pathParam:"style=simple,explode=false,name=span_id"`
	CreateSpanMetricRequest components.CreateSpanMetricRequest `request:"mediaType=application/json"`
}

func (o *CreateMetricSpansSpanIDMetricsPostRequest) GetSpanID() string {
	if o == nil {
		return ""
	}
	return o.SpanID
}

func (o *CreateMetricSpansSpanIDMetricsPostRequest) GetCreateSpanMetricRequest() components.CreateSpanMetricRequest {
	if o == nil {
		return components.CreateSpanMetricRequest{}
	}
	return o.CreateSpanMetricRequest
}

type CreateMetricSpansSpanIDMetricsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	CreateSpanMetricResponse *components.CreateSpanMetricResponse
}

func (o *CreateMetricSpansSpanIDMetricsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateMetricSpansSpanIDMetricsPostResponse) GetCreateSpanMetricResponse() *components.CreateSpanMetricResponse {
	if o == nil {
		return nil
	}
	return o.CreateSpanMetricResponse
}
