// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteSpanSpansSpanIDDeleteRequest struct {
	// The ID of the span to delete
	SpanID string `pathParam:"style=simple,explode=false,name=span_id"`
}

func (o *DeleteSpanSpansSpanIDDeleteRequest) GetSpanID() string {
	if o == nil {
		return ""
	}
	return o.SpanID
}

type DeleteSpanSpansSpanIDDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteSpanSpansSpanIDDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
