// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteCustomModelModelsCustomModelIDDeleteRequest struct {
	// The ID of the custom language model to delete
	ModelID string `pathParam:"style=simple,explode=false,name=model_id"`
}

func (o *DeleteCustomModelModelsCustomModelIDDeleteRequest) GetModelID() string {
	if o == nil {
		return ""
	}
	return o.ModelID
}

type DeleteCustomModelModelsCustomModelIDDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteCustomModelModelsCustomModelIDDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
