// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type FunctionCallCallPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	AppAPIPublicV2FunctionCallCallFunctionResponse *components.AppAPIPublicV2FunctionCallCallFunctionResponse
}

func (o *FunctionCallCallPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *FunctionCallCallPostResponse) GetAppAPIPublicV2FunctionCallCallFunctionResponse() *components.AppAPIPublicV2FunctionCallCallFunctionResponse {
	if o == nil {
		return nil
	}
	return o.AppAPIPublicV2FunctionCallCallFunctionResponse
}
