// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetCustomModelModelsCustomModelIDGetRequest struct {
	// The ID of the custom language model to get
	ModelID string `pathParam:"style=simple,explode=false,name=model_id"`
}

func (o *GetCustomModelModelsCustomModelIDGetRequest) GetModelID() string {
	if o == nil {
		return ""
	}
	return o.ModelID
}

type GetCustomModelModelsCustomModelIDGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	GetCustomModelResponse *components.GetCustomModelResponse
}

func (o *GetCustomModelModelsCustomModelIDGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetCustomModelModelsCustomModelIDGetResponse) GetGetCustomModelResponse() *components.GetCustomModelResponse {
	if o == nil {
		return nil
	}
	return o.GetCustomModelResponse
}
