// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetDatasetEntryDatasetsDatasetIDEntriesEntryIDGetRequest struct {
	// The id of the dataset
	DatasetID string `pathParam:"style=simple,explode=false,name=dataset_id"`
	// The id of the entry to get
	EntryID string `pathParam:"style=simple,explode=false,name=entry_id"`
}

func (o *GetDatasetEntryDatasetsDatasetIDEntriesEntryIDGetRequest) GetDatasetID() string {
	if o == nil {
		return ""
	}
	return o.DatasetID
}

func (o *GetDatasetEntryDatasetsDatasetIDEntriesEntryIDGetRequest) GetEntryID() string {
	if o == nil {
		return ""
	}
	return o.EntryID
}

type GetDatasetEntryDatasetsDatasetIDEntriesEntryIDGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	GetDatasetEntryResponse *components.GetDatasetEntryResponse
}

func (o *GetDatasetEntryDatasetsDatasetIDEntriesEntryIDGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetDatasetEntryDatasetsDatasetIDEntriesEntryIDGetResponse) GetGetDatasetEntryResponse() *components.GetDatasetEntryResponse {
	if o == nil {
		return nil
	}
	return o.GetDatasetEntryResponse
}
