// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetUploadURLKnowledgeKnowledgeBaseIDUploadURLGetRequest struct {
	// The id of the knowledge base to get the upload URL for
	KnowledgeBaseID string `pathParam:"style=simple,explode=false,name=knowledge_base_id"`
	// The filename of the file to upload
	Filename string `queryParam:"style=form,explode=true,name=filename"`
}

func (o *GetUploadURLKnowledgeKnowledgeBaseIDUploadURLGetRequest) GetKnowledgeBaseID() string {
	if o == nil {
		return ""
	}
	return o.KnowledgeBaseID
}

func (o *GetUploadURLKnowledgeKnowledgeBaseIDUploadURLGetRequest) GetFilename() string {
	if o == nil {
		return ""
	}
	return o.Filename
}

type GetUploadURLKnowledgeKnowledgeBaseIDUploadURLGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	GetUploadURLResponse *components.GetUploadURLResponse
}

func (o *GetUploadURLKnowledgeKnowledgeBaseIDUploadURLGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetUploadURLKnowledgeKnowledgeBaseIDUploadURLGetResponse) GetGetUploadURLResponse() *components.GetUploadURLResponse {
	if o == nil {
		return nil
	}
	return o.GetUploadURLResponse
}
