// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type QueryKnowledgeBaseKnowledgeKnowledgeBaseIDQueryPostRequest struct {
	// The id of the knowledge base to query
	KnowledgeBaseID           string                               `pathParam:"style=simple,explode=false,name=knowledge_base_id"`
	QueryKnowledgeBaseRequest components.QueryKnowledgeBaseRequest `request:"mediaType=application/json"`
}

func (o *QueryKnowledgeBaseKnowledgeKnowledgeBaseIDQueryPostRequest) GetKnowledgeBaseID() string {
	if o == nil {
		return ""
	}
	return o.KnowledgeBaseID
}

func (o *QueryKnowledgeBaseKnowledgeKnowledgeBaseIDQueryPostRequest) GetQueryKnowledgeBaseRequest() components.QueryKnowledgeBaseRequest {
	if o == nil {
		return components.QueryKnowledgeBaseRequest{}
	}
	return o.QueryKnowledgeBaseRequest
}

type QueryKnowledgeBaseKnowledgeKnowledgeBaseIDQueryPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseQueryKnowledgeBaseKnowledgeKnowledgeBaseIDQueryPost []components.QueryKnowledgeBaseResponse
}

func (o *QueryKnowledgeBaseKnowledgeKnowledgeBaseIDQueryPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *QueryKnowledgeBaseKnowledgeKnowledgeBaseIDQueryPostResponse) GetResponseQueryKnowledgeBaseKnowledgeKnowledgeBaseIDQueryPost() []components.QueryKnowledgeBaseResponse {
	if o == nil {
		return nil
	}
	return o.ResponseQueryKnowledgeBaseKnowledgeKnowledgeBaseIDQueryPost
}
