// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type SaveToDatasetSpansSpanIDSaveExamplesPostRequest struct {
	SpanID string `pathParam:"style=simple,explode=false,name=span_id"`
}

func (o *SaveToDatasetSpansSpanIDSaveExamplesPostRequest) GetSpanID() string {
	if o == nil {
		return ""
	}
	return o.SpanID
}

type SaveToDatasetSpansSpanIDSaveExamplesPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SaveToDatasetResponse *components.SaveToDatasetResponse
}

func (o *SaveToDatasetSpansSpanIDSaveExamplesPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SaveToDatasetSpansSpanIDSaveExamplesPostResponse) GetSaveToDatasetResponse() *components.SaveToDatasetResponse {
	if o == nil {
		return nil
	}
	return o.SaveToDatasetResponse
}
