// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types/stream"
)

type StreamFunctionFunctionsFunctionIDCallStreamPostRequest struct {
	// The id of the function to call
	FunctionID                                 string                                                `pathParam:"style=simple,explode=false,name=function_id"`
	AppAPIPublicV2FunctionsCallFunctionRequest components.AppAPIPublicV2FunctionsCallFunctionRequest `request:"mediaType=application/json"`
}

func (o *StreamFunctionFunctionsFunctionIDCallStreamPostRequest) GetFunctionID() string {
	if o == nil {
		return ""
	}
	return o.FunctionID
}

func (o *StreamFunctionFunctionsFunctionIDCallStreamPostRequest) GetAppAPIPublicV2FunctionsCallFunctionRequest() components.AppAPIPublicV2FunctionsCallFunctionRequest {
	if o == nil {
		return components.AppAPIPublicV2FunctionsCallFunctionRequest{}
	}
	return o.AppAPIPublicV2FunctionsCallFunctionRequest
}

// StreamFunctionFunctionsFunctionIDCallStreamPostData - The actual data payload containing streaming chunk information
type StreamFunctionFunctionsFunctionIDCallStreamPostData struct {
	// Incremental text content generated by the model
	Delta *string `json:"delta,omitempty"`
	// Unique identifier for the execution span
	SpanID *string `json:"span_id,omitempty"`
}

func (o *StreamFunctionFunctionsFunctionIDCallStreamPostData) GetDelta() *string {
	if o == nil {
		return nil
	}
	return o.Delta
}

func (o *StreamFunctionFunctionsFunctionIDCallStreamPostData) GetSpanID() *string {
	if o == nil {
		return nil
	}
	return o.SpanID
}

// StreamFunctionFunctionsFunctionIDCallStreamPostResponseBody - Server-Sent Event following the SSE specification
type StreamFunctionFunctionsFunctionIDCallStreamPostResponseBody struct {
	// Event ID for the SSE event
	ID *string `json:"id,omitempty"`
	// Event type for the SSE event
	Event *string `json:"event,omitempty"`
	// The actual data payload containing streaming chunk information
	Data StreamFunctionFunctionsFunctionIDCallStreamPostData `json:"data"`
	// Retry interval in milliseconds for the SSE connection
	Retry *int64 `json:"retry,omitempty"`
}

func (o *StreamFunctionFunctionsFunctionIDCallStreamPostResponseBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *StreamFunctionFunctionsFunctionIDCallStreamPostResponseBody) GetEvent() *string {
	if o == nil {
		return nil
	}
	return o.Event
}

func (o *StreamFunctionFunctionsFunctionIDCallStreamPostResponseBody) GetData() StreamFunctionFunctionsFunctionIDCallStreamPostData {
	if o == nil {
		return StreamFunctionFunctionsFunctionIDCallStreamPostData{}
	}
	return o.Data
}

func (o *StreamFunctionFunctionsFunctionIDCallStreamPostResponseBody) GetRetry() *int64 {
	if o == nil {
		return nil
	}
	return o.Retry
}

func (o StreamFunctionFunctionsFunctionIDCallStreamPostResponseBody) GetEventEncoding(event string) (string, error) {
	return "application/json", nil
}

type StreamFunctionFunctionsFunctionIDCallStreamPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Server-Sent Events stream of function execution chunks
	Object  *stream.EventStream[StreamFunctionFunctionsFunctionIDCallStreamPostResponseBody]
	Headers map[string][]string
}

func (o *StreamFunctionFunctionsFunctionIDCallStreamPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *StreamFunctionFunctionsFunctionIDCallStreamPostResponse) GetObject() *stream.EventStream[StreamFunctionFunctionsFunctionIDCallStreamPostResponseBody] {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *StreamFunctionFunctionsFunctionIDCallStreamPostResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
