"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from opperai.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ChatCompletionStreamOptionsParamTypedDict(TypedDict):
    include_obfuscation: NotRequired[bool]
    include_usage: NotRequired[bool]


class ChatCompletionStreamOptionsParam(BaseModel):
    include_obfuscation: Optional[bool] = None

    include_usage: Optional[bool] = None
