"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from opperai.types import BaseModel
from opperai.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class ChatCompletionContentPartRefusalParamTypedDict(TypedDict):
    refusal: str
    type: Literal["refusal"]


class ChatCompletionContentPartRefusalParam(BaseModel):
    refusal: str

    TYPE: Annotated[
        Annotated[Literal["refusal"], AfterValidator(validate_const("refusal"))],
        pydantic.Field(alias="type"),
    ] = "refusal"
