"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .openai_types_chat_chat_completion_named_tool_choice_param_function import (
    OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction,
    OpenaiTypesChatChatCompletionNamedToolChoiceParamFunctionTypedDict,
)
from opperai.types import BaseModel
from opperai.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class ChatCompletionNamedToolChoiceParamTypedDict(TypedDict):
    function: OpenaiTypesChatChatCompletionNamedToolChoiceParamFunctionTypedDict
    type: Literal["function"]


class ChatCompletionNamedToolChoiceParam(BaseModel):
    function: OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction

    TYPE: Annotated[
        Annotated[Literal["function"], AfterValidator(validate_const("function"))],
        pydantic.Field(alias="type"),
    ] = "function"
