"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from opperai.types import BaseModel
from opperai.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteCustomModelModelsCustomModelIDDeleteRequestTypedDict(TypedDict):
    model_id: str
    r"""The ID of the custom language model to delete"""


class DeleteCustomModelModelsCustomModelIDDeleteRequest(BaseModel):
    model_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the custom language model to delete"""
