"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from opperai.types import BaseModel
from opperai.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteModelAliasModelsAliasesAliasIDDeleteRequestTypedDict(TypedDict):
    alias_id: str
    r"""The ID of the model alias to delete"""


class DeleteModelAliasModelsAliasesAliasIDDeleteRequest(BaseModel):
    alias_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the model alias to delete"""
