"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from opperai.types import BaseModel
from typing_extensions import TypedDict


class DocumentSegmentTypedDict(TypedDict):
    id: str
    r"""The id of the segment"""
    content: str
    r"""The content of the segment"""


class DocumentSegment(BaseModel):
    id: str
    r"""The id of the segment"""

    content: str
    r"""The content of the segment"""
