"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from opperai.types import BaseModel
from opperai.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetDocumentByKeyKnowledgeKnowledgeBaseIDDocumentsDocumentKeyGetRequestTypedDict(
    TypedDict
):
    knowledge_base_id: str
    r"""The id of the knowledge base"""
    document_key: str
    r"""The key of the document to retrieve"""


class GetDocumentByKeyKnowledgeKnowledgeBaseIDDocumentsDocumentKeyGetRequest(BaseModel):
    knowledge_base_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The id of the knowledge base"""

    document_key: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The key of the document to retrieve"""
