"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from opperai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class OCRDocumentTypedDict(TypedDict):
    r"""Document specification for OCR processing."""

    type: str
    r"""Document type: 'document_url', 'image_url', or 'base64'"""
    document_url: NotRequired[Nullable[str]]
    r"""URL to the document (PDF or image) to process. Use with type='document_url'"""
    image_url: NotRequired[Nullable[str]]
    r"""URL to an image to process. Use with type='image_url'"""
    document_name: NotRequired[Nullable[str]]
    r"""Name of the document. Use with type='base64'"""
    content: NotRequired[Nullable[str]]
    r"""Base64-encoded content of the document. Use with type='base64'"""


class OCRDocument(BaseModel):
    r"""Document specification for OCR processing."""

    type: str
    r"""Document type: 'document_url', 'image_url', or 'base64'"""

    document_url: OptionalNullable[str] = UNSET
    r"""URL to the document (PDF or image) to process. Use with type='document_url'"""

    image_url: OptionalNullable[str] = UNSET
    r"""URL to an image to process. Use with type='image_url'"""

    document_name: OptionalNullable[str] = UNSET
    r"""Name of the document. Use with type='base64'"""

    content: OptionalNullable[str] = UNSET
    r"""Base64-encoded content of the document. Use with type='base64'"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["document_url", "image_url", "document_name", "content"]
        nullable_fields = ["document_url", "image_url", "document_name", "content"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
