"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .listlanguagemodelsresponse import (
    ListLanguageModelsResponse,
    ListLanguageModelsResponseTypedDict,
)
from .meta import Meta, MetaTypedDict
from opperai.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PaginatedResponseListLanguageModelsResponseTypedDict(TypedDict):
    meta: MetaTypedDict
    data: List[ListLanguageModelsResponseTypedDict]
    r"""List of items returned in the response"""


class PaginatedResponseListLanguageModelsResponse(BaseModel):
    meta: Meta

    data: List[ListLanguageModelsResponse]
    r"""List of items returned in the response"""
