"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .listocrmodelsresponse import ListOCRModelsResponse, ListOCRModelsResponseTypedDict
from .meta import Meta, MetaTypedDict
from opperai.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PaginatedResponseListOCRModelsResponseTypedDict(TypedDict):
    meta: MetaTypedDict
    data: List[ListOCRModelsResponseTypedDict]
    r"""List of items returned in the response"""


class PaginatedResponseListOCRModelsResponse(BaseModel):
    meta: Meta

    data: List[ListOCRModelsResponse]
    r"""List of items returned in the response"""
