"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .listtracesresponse import ListTracesResponse, ListTracesResponseTypedDict
from .meta import Meta, MetaTypedDict
from opperai.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PaginatedResponseListTracesResponseTypedDict(TypedDict):
    meta: MetaTypedDict
    data: List[ListTracesResponseTypedDict]
    r"""List of items returned in the response"""


class PaginatedResponseListTracesResponse(BaseModel):
    meta: Meta

    data: List[ListTracesResponse]
    r"""List of items returned in the response"""
