"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .listrerankmodelsresponse import (
    ListRerankModelsResponse,
    ListRerankModelsResponseTypedDict,
)
from .meta import Meta, MetaTypedDict
from opperai.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PaginatedResponseListRerankModelsResponseTypedDict(TypedDict):
    meta: MetaTypedDict
    data: List[ListRerankModelsResponseTypedDict]
    r"""List of items returned in the response"""


class PaginatedResponseListRerankModelsResponse(BaseModel):
    meta: Meta

    data: List[ListRerankModelsResponse]
    r"""List of items returned in the response"""
