"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .listfilesresponse import ListFilesResponse, ListFilesResponseTypedDict
from .meta import Meta, MetaTypedDict
from opperai.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PaginatedResponseListFilesResponseTypedDict(TypedDict):
    meta: MetaTypedDict
    data: List[ListFilesResponseTypedDict]
    r"""List of items returned in the response"""


class PaginatedResponseListFilesResponse(BaseModel):
    meta: Meta

    data: List[ListFilesResponse]
    r"""List of items returned in the response"""
