"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .queryknowledgebaserequest import (
    QueryKnowledgeBaseRequest,
    QueryKnowledgeBaseRequestTypedDict,
)
from opperai.types import BaseModel
from opperai.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class QueryKnowledgeBaseKnowledgeKnowledgeBaseIDQueryPostRequestTypedDict(TypedDict):
    knowledge_base_id: str
    r"""The id of the knowledge base to query"""
    query_knowledge_base_request: QueryKnowledgeBaseRequestTypedDict


class QueryKnowledgeBaseKnowledgeKnowledgeBaseIDQueryPostRequest(BaseModel):
    knowledge_base_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The id of the knowledge base to query"""

    query_knowledge_base_request: Annotated[
        QueryKnowledgeBaseRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
