"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from opperai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class RegisterCustomModelRequestTypedDict(TypedDict):
    name: str
    r"""The name of the custom language model"""
    identifier: str
    r"""The identifier of the custom language model"""
    extra: NotRequired[Dict[str, Any]]
    r"""Extra metadata about the custom language model"""
    api_key: NotRequired[Nullable[str]]
    r"""The API key of the custom language model"""


class RegisterCustomModelRequest(BaseModel):
    name: str
    r"""The name of the custom language model"""

    identifier: str
    r"""The identifier of the custom language model"""

    extra: Optional[Dict[str, Any]] = None
    r"""Extra metadata about the custom language model"""

    api_key: OptionalNullable[str] = UNSET
    r"""The API key of the custom language model"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["extra", "api_key"]
        nullable_fields = ["api_key"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
