"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from opperai.types import BaseModel
from typing_extensions import TypedDict


class RegisterFileUploadResponseTypedDict(TypedDict):
    id: str
    key: str
    original_filename: str
    document_id: int


class RegisterFileUploadResponse(BaseModel):
    id: str

    key: str

    original_filename: str

    document_id: int
