"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from opperai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class SubmitFeedbackRequestTypedDict(TypedDict):
    score: float
    r"""Feedback score (0.0=negative, 1.0=positive)"""
    comment: NotRequired[Nullable[str]]
    r"""Optional comment explaining the feedback"""
    save_to_dataset: NotRequired[Nullable[bool]]
    r"""Force save to dataset (True=force save, False=never save, None=use auto-save config)"""


class SubmitFeedbackRequest(BaseModel):
    score: float
    r"""Feedback score (0.0=negative, 1.0=positive)"""

    comment: OptionalNullable[str] = UNSET
    r"""Optional comment explaining the feedback"""

    save_to_dataset: OptionalNullable[bool] = UNSET
    r"""Force save to dataset (True=force save, False=never save, None=use auto-save config)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["comment", "save_to_dataset"]
        nullable_fields = ["comment", "save_to_dataset"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
