"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatespanrequest import UpdateSpanRequest, UpdateSpanRequestTypedDict
from opperai.types import BaseModel
from opperai.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateSpanSpansSpanIDPatchRequestTypedDict(TypedDict):
    span_id: str
    r"""The ID of the span to update"""
    update_span_request: UpdateSpanRequestTypedDict


class UpdateSpanSpansSpanIDPatchRequest(BaseModel):
    span_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the span to update"""

    update_span_request: Annotated[
        UpdateSpanRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
