"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .oppererror import OpperError
from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .apierror import APIError
    from .badrequesterror import BadRequestError, BadRequestErrorData
    from .conflicterror import ConflictError, ConflictErrorData
    from .error import Error, ErrorData
    from .no_response_error import NoResponseError
    from .notfounderror import NotFoundError, NotFoundErrorData
    from .requestvalidationerror import (
        RequestValidationError,
        RequestValidationErrorData,
    )
    from .responsevalidationerror import ResponseValidationError
    from .unauthorizederror import UnauthorizedError, UnauthorizedErrorData

__all__ = [
    "APIError",
    "BadRequestError",
    "BadRequestErrorData",
    "ConflictError",
    "ConflictErrorData",
    "Error",
    "ErrorData",
    "NoResponseError",
    "NotFoundError",
    "NotFoundErrorData",
    "OpperError",
    "RequestValidationError",
    "RequestValidationErrorData",
    "ResponseValidationError",
    "UnauthorizedError",
    "UnauthorizedErrorData",
]

_dynamic_imports: dict[str, str] = {
    "APIError": ".apierror",
    "BadRequestError": ".badrequesterror",
    "BadRequestErrorData": ".badrequesterror",
    "ConflictError": ".conflicterror",
    "ConflictErrorData": ".conflicterror",
    "Error": ".error",
    "ErrorData": ".error",
    "NoResponseError": ".no_response_error",
    "NotFoundError": ".notfounderror",
    "NotFoundErrorData": ".notfounderror",
    "RequestValidationError": ".requestvalidationerror",
    "RequestValidationErrorData": ".requestvalidationerror",
    "ResponseValidationError": ".responsevalidationerror",
    "UnauthorizedError": ".unauthorizederror",
    "UnauthorizedErrorData": ".unauthorizederror",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
