"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from opperai.errors import OpperError
from opperai.types import BaseModel
from typing import Any, Optional


class BadRequestErrorData(BaseModel):
    detail: Any
    r"""The detail of the error"""

    type: Optional[str] = "BadRequestError"

    message: Optional[str] = "The request is invalid"


class BadRequestError(OpperError):
    data: BadRequestErrorData

    def __init__(
        self,
        data: BadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
