"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from opperai.errors import OpperError
from opperai.types import BaseModel
from typing import Any, Optional


class RequestValidationErrorData(BaseModel):
    detail: Any
    r"""Where the error occurred and the error message"""

    type: Optional[str] = "RequestValidationError"

    message: Optional[str] = "The request is invalid"


@dataclass(frozen=True)
class RequestValidationError(OpperError):
    data: RequestValidationErrorData = field(hash=False)

    def __init__(
        self,
        data: RequestValidationErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
