"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "opperai"
__version__: str = "1.0.0"
__openapi_doc_version__: str = "2.0.0"
__gen_version__: str = "2.638.5"
__user_agent__: str = "speakeasy-sdk/python 1.0.0 2.638.5 2.0.0 opperai"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
