// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type BadRequestError struct {
	Type    *string `default:"BadRequestError" json:"type"`
	Message *string `default:"The request is invalid" json:"message"`
	// The detail of the error
	Detail   any                     `json:"detail"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &BadRequestError{}

func (e *BadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
