// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type ConflictError struct {
	Type    *string `default:"ConflictError" json:"type"`
	Message *string `default:"The resource already exists" json:"message"`
	// The detail of the error
	Detail   any                     `json:"detail"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ConflictError{}

func (e *ConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
