// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type RequestValidationError struct {
	Type    *string `default:"RequestValidationError" json:"type"`
	Message *string `default:"The request is invalid" json:"message"`
	// Where the error occurred and the error message
	Detail   any                     `json:"detail"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &RequestValidationError{}

func (e *RequestValidationError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
